### ISSUE TITLE
SubmissionQRCodeScanFragment usage

### ISSUE THREAD

**Issue by PeterLombaerts** [covid-be-app/cwa-app-android#110]
More of a question than an issue:
I noticed a barcode scanner activity was included in the manifest, and in the German package I've noticed a SubmissionQRCodeScanFragment class, but I can't find if (or where) it's used in the Belgian version. 
Is there a functionality in the pipeline to be able to submit test results via a qr code?
Of is there a different purpose for this?

**Comment by leroynicolasalexi** [comment]
It is not used in the Belgian version, and no current plan to add a qr scanner. That fragment & dependency could be entirely removed.
