### ISSUE TITLE
App stopped updating

### ISSUE THREAD

**Issue by Emilv2** [covid-be-app/cwa-app-android#127]
My corona app on Android 10 hasn't been doing daily updates for a few days now. It seems like I'm not the only one: https://old.reddit.com/r/belgium/comments/ksbufi/corona_app_stopped_updating_am_i_alone/

**Comment by swtimmer** [comment]
Same issue here. The last update of data was on January 5th. Let me know if you need me to provide any debug information.

**Comment by Jatarii** [comment]
Here too: Android 11 Samsung Galaxy S20

**Comment by Mopper** [comment]
Same here: last updated: 5 Jan, 01:24 (CET).

**Comment by leroynicolasalexi** [comment]
Thanks for the report. Investigating...

**Comment by tanguyr** [comment]
here as well: last update 5 Jan, 01:55
Android 11 Pixel 3

**Comment by gitovino** [comment]
Same here. 04/01

**Comment by Emilv2** [comment]
I just updated to 1.11.1, but the problem is not fixed for me. Last update is still Jan 3,5:29 PM.

**Comment by swtimmer** [comment]
> Thanks for the report. Investigating...

Got the latest update but still no working sync!

**Comment by robvdw2** [comment]
Same problem here. Updated to 1.11.1 yesterday, but the data is still stuck on Jan 5 today. (Android 11, OnePlus 8, all 4 settings in the app are on)

**Comment by JVApen** [comment]
Same problem here, I assume device independent.
Anyhow: Moto Z Play with Android 8
Also running 1.11.1

**Comment by leroynicolasalexi** [comment]
Do you also have no exposure checks in the google exposure notifications menu ?

**Comment by wouterh** [comment]
I have 1.11.1 installed on a oneplus 6 with android 10. It's still not updating (since Jan 5th).

I do have checks in the google exposure notifications menu.

Is there anything I can do to help debug? I had a quick look in `adb logcat`, but I didn't see any obvious error messages.

**Comment by robvdw2** [comment]
> Do you also have no exposure checks in the google exposure notifications menu ?

Google: last checked for potential exposure today at 01:07
App: Updated 5 Jan, 07:15

**Comment by JVApen** [comment]
I've also just checked, Google API indicates checks from today, app is stuck on 5th of January

**Comment by Emilv2** [comment]
Same thing over here, last exposure check was today but the app is still stuck on Jan 3. Weekly averages are still being updated.

**Comment by leroynicolasalexi** [comment]
Thanks for the help, the upcoming update should fix the issue. App should sync the day of the installed update after 00:00 UTC

**Comment by swtimmer** [comment]
> Thanks for the help, the upcoming update should fix the issue. App should sync the day of the installed update after 00:00 UTC

Thanks for your hard work!

**Comment by Jixop-github** [comment]
Same issue. 
![Screenshot_20210111_100407_be sciensano coronalert~2](https://user-images.githubusercontent.com/77269338/104163068-14be2d00-53f6-11eb-9e84-373a314bd97a.jpg)

**Comment by kev-out** [comment]
Version 1.11.2 is now live on the [Play Store](https://play.google.com/store/apps/details?id=be.sciensano.coronalert&hl=en)

**Comment by ir-fuel** [comment]
This issue should be resolved now. If there are other problems please make a new ticket.

Thanks for reporting.

**Comment by tanguyr** [comment]
actually, I was waiting for tomorrow to confirm, but the issue is *not* fixed for me...

updated to 1.11. 2 yesterday, still no updates

**Comment by wouterh** [comment]
Mine updated yesterday, but didn't again update today. ![Screenshot_20210113-135719.jpg](https://user-images.githubusercontent.com/688159/104455331-6c4fca80-55a7-11eb-9ec9-f40b2e29a6e6.jpg)

**Comment by ir-fuel** [comment]
https://www.theverge.com/2021/1/13/22228594/google-coronavirus-tracking-app-exposure-notifications-issues-problems

**Comment by Jixop-github** [comment]
Mine updated upon opening the app.
