### ISSUE TITLE
App is no longer updating

### ISSUE THREAD

**Issue by gcp** [covid-be-app/cwa-app-android#129]
Issue #127 was closed but the app is still just as broken.

I received the 1.11.2 update on the Play Store yesterday. It's now past 12hrs the next day and the last update is still stuck at Jan 5.

**Comment by gcp** [comment]
Is this related? https://twitter.com/CoronalertBe/status/1349313209900163072

**Comment by tanguyr** [comment]
> Issue #127 was closed but the app is still just as broken.
> 
> I received the 1.11.2 update on the Play Store yesterday. It's now past 12hrs the next day and the last update is still stuck at Jan 5.

same issue here

**Comment by leroynicolasalexi** [comment]
There is currently another issue with the google exposure notification api affecting not only coronalert but other covid apps. You can find more details about the issue here: https://github.com/corona-warn-app/cwa-app-android/issues/2081.

**Comment by tanguyr** [comment]
well, whatever it was it seems to be fixed, app status updated today at 18:25
