### ISSUE TITLE
Huge data communication (> 10 GB in a few hours)

### ISSUE THREAD

**Issue by benoitdevos** [covid-be-app/cwa-app-android#131]
On saturday 16th, Coronalert Android app basically used all my monthly plan, i.e. 13.72 GB out of 15, in a few hours. At that moment my network supplier suspended my 4G connection - so I suspect it would have been much worse. You will find hereafter a screenshot of the standard Android data usage report.

Please note that Coronalert is also listed at the top my WIFI data consumption app list, with a lower, but still high, amount of data: 734 MB out of 2.97 GB.
___

![coronalert_data_usage2](https://user-images.githubusercontent.com/4092710/104846995-e51f9100-58dd-11eb-8fbd-4d99399a522e.png)

**Comment by Jan-PieterBaert** [comment]
Perhaps a setting to only use wifi could be useful (and also decreasing the data usage)

**Comment by benoitdevos** [comment]
> 
> 
> Perhaps a setting to only use wifi could be useful (and also decreasing the data usage)

Such a setting already exist. I discovered it too late.

**Comment by dronzal** [comment]
seems to be the same issue I encountered #130

**Comment by leroynicolasalexi** [comment]
I'm sorry for that. Which version do you have ? An issue that could explains higher data consomption was fixed with 1.11.2

**Comment by dronzal** [comment]
@leroynicolasalexi, in my case (#130), the issue occured when app was already updated to 1.11.2

**Comment by benoitdevos** [comment]
@leroynicolasalexi 
> 
> 
> I'm sorry for that. Which version do you have ? An issue that could explains higher data consomption was fixed with 1.11.2

No I had already 1.11.2 at that moment.

**Comment by benoitdevos** [comment]
@leroynicolasalexi  Can you link the corresponding commits that made you close this issue ?

**Comment by leroynicolasalexi** [comment]
https://github.com/covid-be-app/cwa-app-android/commit/4ed458133fe61772324ae30f292f3bdc4eb750f5

**Comment by benoitdevos** [comment]
> 
> 
> [4ed4581](https://github.com/covid-be-app/cwa-app-android/commit/4ed458133fe61772324ae30f292f3bdc4eb750f5)

But I had already version 1.11.2 when I submited this issue.
