### ISSUE TITLE
Clarify whether failed dummy requests are retransmitted

### ISSUE THREAD

**Issue by gunesacar** [covid-be-app/cwa-app-android#132]
Hello,

_This is a question about the behavior of the Coronalert apps. Please let me know if there is a better place to ask it._

I'm helping Prof. Bart Preneel to calculate the active number of Coronalert users.

The method I'm looking into is similar to [the Swiss method](https://www.experimental.bfs.admin.ch/expstat/en/home/innovative-methods/swisscovid-app-monitoring.assetdetail.13667538.html), which is based on the number of dummy requests on the backend.

I am wondering if the following statement mentioned in [the Swiss document](https://www.experimental.bfs.admin.ch/bfsstatic/dam/assets/13667538/master) is also valid for Coronalert apps:
> It should be noted that if the device is not active or is not connected to the internet, the dummy request is transmitted later on.

That is, do Coronalert apps (Android + iOS) resend dummy requests that are failed due to connectivity (or other) issues?

Thank you so much!

**Comment by leroynicolasalexi** [comment]
Hi, 

It is valid for android. App does not attempt to send dummy requests if there is no connectivity but will do as soon as connectivity returns in a 2h window.

**Comment by gunesacar** [comment]
Thank so much, @leroynicolasalexi 

Just to clarify, does that mean previously failed dummies can be dropped if the connectivity does not return in 2 hours --  e.g. when the phone is in airplane mode through the night?

**Comment by leroynicolasalexi** [comment]
Yes, requests doesn't accumulate. If requests can't be sent within 2h they will simply be ignored until the next 2h window start sending new ones.

**Comment by gunesacar** [comment]
Thank you.
