### ISSUE TITLE
Problem in terms and conditions

### ISSUE THREAD

**Issue by roidelapluie** [covid-be-app/cwa-app-android#70]
At least in French, the terms and conditions specify that some data can be shared with other EU countries.

It seems that coronalert.be also specifies that Switzerland is included in the countries (and they use the same protocol). As Switzerland is not part of the EU, the terms inside the app should be adapted, or the website of coronalert.

**Comment by leroynicolasalexi** [comment]
Thank you, I'm forwarding this to the team
