### ISSUE TITLE
Improvement suggestion - Remove Timber and Log classes when building the app via Proguard

### ISSUE THREAD

**Issue by kvandermast** [covid-be-app/cwa-app-android#72]
In the Application class, you configure the Timber logging framework to be used in when Build.DEBUG = true.

````
        if (BuildConfig.DEBUG) {
            Timber.plant(Timber.DebugTree())
        }
````

in your code, you duplicate - unnecessarily - the check on the DEBUG build state (e.g. BackgroundWorkScheduler.kt)

````
 if (BuildConfig.DEBUG) Timber.d("Work type $tag is active: $active")
````

- Timber is set-up to avoid this check;
- From a first glance, it seems that the proguard rules don't define the remove of both Timber.x or Log.x, eg.

`````
# remove android.util.Log
-assumenosideeffects class android.util.Log {
   public static *** v(...);
   public static *** d(...);
   public static *** i(...);
   public static *** w(...);
}

# remove timber.log.Timber
-assumenosideeffects class timber.log.Timber {
    public static *** v(...);
    public static *** d(...);
}
`````

It is a good practice of removing the statements from the code on minification.

**Comment by leroynicolasalexi** [comment]
Thanks for the feedback, indeed, unnecessary check could be removed
