### ISSUE TITLE
Few typos in the french translation

### ISSUE THREAD

**Issue by delaere** [covid-be-app/cwa-app-android#74]
I am currently on the beta in french and noted few minor typos:

1. In the "statistics" box on the front page, the percentages do not appear with the + sign. The meaning is therefore not obvious. I have seen a screenshot of the en version were out is present ( so +50% instead of simply 50%)

2. In the "risk" box, the update time reads as : 
`Mise à jour : aujourd'hui 'à' 03:39`
with the à in spurious quotes.

3. In the test result box, one reads:
`Générez le code pour recevoir votre résultat test sur votre smartphone`
while it should be:
`Générez le code pour recevoir votre résultat de  test sur votre smartphone`
or even better:
`Générez le code pour recevoir le résultat de votre test sur votre smartphone.`

Hope it helps 🙂

**Comment by leroynicolasalexi** [comment]
Thanks for the feedback, we will fix it :)
