### ISSUE TITLE
Android 10: Battery optimization on "intelligent" instead of "don't optimize"

### ISSUE THREAD

**Issue by Forceflow** [covid-be-app/cwa-app-android#77]
**Device:** Oneplus 5
**Android version:** 10.0
**App version:** 1.5.4 (origin: Play Store)

On my (vanilla) Android 10 system, the introductory wizard explains how the background battery optimization should be turned off for optimal usage of the app, and the in-app slider confirms that the setting is configured correctly.

But when I manually go to the Android settings and check battery optimization on a per-app basis, I see the Coronalert app is still on the default "intelligent" (and thus, interruptable whenever Android feels like it) setting. I am under the impression that it should be set to "don't optimize", but this is something a regular end-user probably isn't going to do.

Is this a problem for app functionality or working as expected?

![coronalert](https://user-images.githubusercontent.com/3607063/94133627-33a5ad00-fe61-11ea-8e22-319b5b5ec816.jpg)
![coronalert_intelligent](https://user-images.githubusercontent.com/3607063/94133617-31435300-fe61-11ea-889a-14a7c73d8478.jpg)

**Comment by roidelapluie** [comment]
Note that this should not prevent the app to log the contacts ; it will just only download data from the central server less often to let you know if you have been in close contact, I think.

**Comment by Forceflow** [comment]
Okay, that's not a big problem then, I guess. Android permissions are a jungle.

**Comment by leroynicolasalexi** [comment]
Hi, thanks for the feedback. 
App is asking the OS to whitelist the app from battery optimization, but it's up to the OS to implement that 
more or less correctly from my understanding. I can reproce this myself on oneplus, but the flag in code still says the battery optimization is disabled, so I don't know if it has an effect or not on that particular device
