### ISSUE TITLE
Possibility to see the number of "negative contacts" and total number of users?

### ISSUE THREAD

**Issue by niconoe** [covid-be-app/cwa-app-android#81]
Hey,

I'm using the app since a week now, and thankfully I always get the "limited risk - no exposure yet" green message. 

However, I have no idea if this of how many people are using the app in Belgium for the moment, nor of how many users I've crossed/exchanged keys with. I think it would give some context: it's quite different to have a limited exposure because I've had contact with many "negative" people, than to have this green light because few people are using the app yet, and so maybe I've had contacts with all of them.

I think displaying those two metrics (total/daily number of app users + number of "negative contacts") somewhere in the app would be great, is that feasible?

Anyway, thanks for the good work!

**Comment by Forceflow** [comment]
I've been thinking about this as well. On the one hand, it would help people to verify that the app is actually working, on the other hand it might lead to reckless experimentation / boundary testing on racking up numbers (It is the age of incredibly dumb social media challenges, after all).

**Comment by ir-fuel** [comment]
There is no way of knowing with how many users you have exchanged keys. The system does not expose this kind of information. This is hidden inside iOS and Android.

The only keys that go through the code and are accessible to developers are the keys of users that have tested positive and decided to upload theirs. These will be downloaded and are matched on your device. A list of keys is sent to the EN API, and the API returns a match count. However, that match count doesn't say anything about the number of different users you might have encountered, as keys rotate so 5 matches could be linked to 1 phone, for instance.

**Comment by Snorkeldink** [comment]
This app https://github.com/mh-/corona-warn-companion-android which will show some of this information (requires root)
