### ISSUE TITLE
Doesnt work without Google Play Services

### ISSUE THREAD

**Issue by maartendebal** [covid-be-app/cwa-app-android#85]
The app doesn't work on a Lineage Android build.
Will the app be supported on a naked Android build?

LineageOS: 14.1-20190720
Android: 7.1.2
Device: HTC One A9

**Comment by editicalu** [comment]
Considering the responses on #69 and the German app (from which this is a fork) has the [same issues](https://github.com/corona-warn-app/cwa-app-android#known-issues), I don't think that's gonna be the case.

**Comment by sdebruyn** [comment]
How would it be able to work without the Play Services?

https://developers.google.com/android/exposure-notifications/exposure-notifications-api

**Comment by dylanjan313** [comment]
It works fine by "faking" Play Services with microG + Xposed (for signature spoofing) + FakeGApps
microG (which is open source) implemented the Exposure Notification API (which is made open source too, by Google)

https://github.com/microg/android_packages_apps_GmsCore/issues/1057
https://github.com/google/exposure-notifications-internals

**Comment by ir-fuel** [comment]
I am sorry but this is not something that will be supported in the future.

**Comment by Danacus** [comment]
I can confirm that this works on microG for LineageOS 16.0. Official support would have been nice, but at least it works.
