### ISSUE TITLE
HTTP connection errors

### ISSUE THREAD

**Issue by filipmaelbrancke** [covid-be-app/cwa-app-android#87]
I run all the traffic on my phone through vpn servers (under my control). Currently I'm running a vpn server in the Digital Ocean NYC region. (ASN 14061: https://ipinfo.io/AS14061)
The app constantly throws http 403 (Cause: 4000 - "Something went wrong") errors.
When I disable my vpn connection (or exclude this app from the vpn connection), I have no such errors.

Is traffic through Digital Ocean blocked?   If so, could you provide some more information please? Are there ASNs that are blocked?

**Comment by leroynicolasalexi** [comment]
Server accepts connection from europeans countries only

**Comment by filipmaelbrancke** [comment]
Why would you put these kind of artificial restrictions in? This is a general-purpose app, why limit the possible ways the ip packets flow from a phone to the backend?
Having traffic appear from non-European ip addresses might be a use case for a small number of users, but it's a legitimate use nonetheless.

Besides, could you at least put in a meaningful error message?
