### ISSUE TITLE
CwaUnknownHostException when starting the application

### ISSUE THREAD

**Issue by bigon** [covid-be-app/cwa-app-android#89]
Hello,

Since this morning I get the following exception when starting the application:

```
10-03 07:54:32.695 17788 17788 W System.err: de.rki.coronawarnapp.exception.http.CwaUnknownHostException: error during web request, http status 901
10-03 07:54:32.695 17788 17788 W System.err: 	at de.rki.coronawarnapp.http.HttpErrorParser.intercept(HttpErrorParser.kt:69)
10-03 07:54:32.696 17788 17788 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
10-03 07:54:32.696 17788 17788 W System.err: 	at de.rki.coronawarnapp.http.interceptor.RetryInterceptor.intercept(RetryInterceptor.kt:15)
10-03 07:54:32.696 17788 17788 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
10-03 07:54:32.696 17788 17788 W System.err: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:152)
10-03 07:54:32.696 17788 17788 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
10-03 07:54:32.696 17788 17788 W System.err: 	at de.rki.coronawarnapp.http.interceptor.WebSecurityVerificationInterceptor.intercept(WebSecurityVerificationInterceptor.kt:11)
10-03 07:54:32.696 17788 17788 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
10-03 07:54:32.696 17788 17788 W System.err: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
10-03 07:54:32.696 17788 17788 W System.err: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
10-03 07:54:32.696 17788 17788 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-03 07:54:32.696 17788 17788 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-03 07:54:32.696 17788 17788 W System.err: 	at java.lang.Thread.run(Thread.java:919)
```
~~The only URL I find in the code that is not resolving is `DOWNLOAD_CDN_URL=https://c19distcdn-stg.ixor.be`~~

~~Edit: See below, it seems to be related to Proximus DNS servers~~

Edit2: Might not be proximus fault after all, see https://github.com/covid-be-app/cwa-app-android/issues/89#issuecomment-703085769 and https://github.com/covid-be-app/cwa-app-android/issues/89#issuecomment-703086341

**Comment by bigon** [comment]
So apparently this is randomly happening with proximus DNS servers:

```
bigon@fornost:~$ dig c19distcdn-stg.ixor.be @195.238.2.21 +short
<nothing>
bigon@fornost:~$ dig c19distcdn-stg.ixor.be @195.238.2.21 +short
13.225.238.95
13.225.238.97
13.225.238.66
13.225.238.113
```
From experience, proximus DNS (195.238.2.21/195.238.2.22) are behind a loadbalancer and not all the servers are running the same version of the software. Some are not working well with DNSSEC and apparently also big replies (you have here multiple A records that made the reply bigger than 512 bytes, so is it even supporting EDNS?)

Queries to other DNS servers are working fine:

```
$ dig c19distcdn-stg.ixor.be @1.1.1.1 +short
13.225.238.66
13.225.238.97
13.225.238.113
13.225.238.95
$ dig c19distcdn-stg.ixor.be @1.1.1.1 +short
13.225.238.66
13.225.238.113
13.225.238.95
13.225.238.97
```

Has anybody here a contact at proximus?

**Comment by ir-fuel** [comment]
Thanks a lot for the report @bigon . We are investigating the issue.

**Comment by DJefke** [comment]
The problem is also persistent when I switch from Wlan (Proximus) to 4G (Orange).

**Comment by bigon** [comment]
@DJefke I switched from proximus (Fixes internet/4G to Base 4G) and the application is working after that

**Comment by bigon** [comment]
Looking at twitter, the number of impacted user is raising

**Comment by ir-fuel** [comment]
Unfortunately there is not much we can do on our side. We are trying to get it resolved. I can confirm your findings.

**Comment by bigon** [comment]
@ir-fuel wait, I think my initial assessment was not OK

`dig c19distcdn-stg.ixor.be @1.1.1.1 +short` is now also not giving me any results...

Looks like some caches are now expiring and that means that the problem is maybe not coming from Proximus DNS servers after all (sorry to them, but you still have an issue guys)

**Comment by bigon** [comment]
@ir-fuel DNS is a pain...

According to the [whois](https://www.dnsbelgium.be/fr/whois/info/ixor.be/details), the `ixor.be` zone is hosted at 4 DNS servers:
![image](https://user-images.githubusercontent.com/264358/94990002-1ebfcc80-0579-11eb-9123-c84dfc6461c2.png)

But only 3 of the 4 servers are giving a reply:
```
$ dig c19statcdn-stg.ixor.be @ns-718.awsdns-25.net +short
$ dig c19statcdn-stg.ixor.be  +short @ns-3.awsdns-00.com
13.225.238.66
13.225.238.97
13.225.238.95
13.225.238.113
$ dig c19statcdn-stg.ixor.be  +short @ns-1149.awsdns-15.org
13.225.238.97
13.225.238.113
13.225.238.95
13.225.238.66
$ dig c19statcdn-stg.ixor.be  +short @ns-1825.awsdns-36.co.uk
13.225.238.97
13.225.238.113
13.225.238.66
13.225.238.95
```
So the problem could by the owner of the `ixor.be` I believe

**Comment by bigon** [comment]
I see that you removed `ns-718.awsdns-25.net` from the parent zone, `dig c19distcdn-stg.ixor.be @1.1.1.1 +short` is giving me a result again so that's good

Queries on Proximus DNS servers are still not always giving me an answer (30%-50% failure), I don't know if this is due the caching and/or in a difference in the configuration of the servers behind the loadbalancer.

But indeed I don't think you can do anything for that

**Comment by ir-fuel** [comment]
The problem has been resolved.
Thanks for the report!
