### ISSUE TITLE
Are URL defined in gradle.properties staging URL's

### ISSUE THREAD

**Issue by bigon** [covid-be-app/cwa-app-android#90]
Hello,

Looking at the gradle.properties file, I see the `stg` suffix in the URL's.

Aren't these staging URL's?

Replacing `stg`with `prd` is also resolving here, but with different address:

```
$ dig c19-submission-stg.ixor.be +short
lb-covid19-stg-albext-1121372865.eu-central-1.elb.amazonaws.com.
18.194.80.254
18.157.140.38
3.122.78.133
$ dig c19-submission-prd.ixor.be +short
lb-covid19-prd-albext-1921527101.eu-central-1.elb.amazonaws.com.
18.159.79.26
52.58.119.36
54.93.158.53
```

Are these used in the published build?

**Comment by leroynicolasalexi** [comment]
`prd` is used in published build indeed

**Comment by bigon** [comment]
Thanks for the reply
