### ISSUE TITLE
oorzaak 4000  (problem seems to be related to the proximus DNS see Issue #89)

### ISSUE THREAD

**Issue by FirelightLokeren** [covid-be-app/cwa-app-android#91]
Hi, I'm a beta tester and when I open the app i got an error message.

OORZAAK: 4000
Er is iets fout gegaan.

Error during web request, http status 901

In attach the screenshots of the detail of the error message.

I'm using an Samsung S8 plus running and Android Version 9. G955FXXSADTI1
The version of Coronalert is 1.6.0

My girlfriend has the same problem on an Samsung S10 running android Version 10. G970FXXU8DTH7

Kind regards 

Koen Deschepper
 

![Screenshot_20201003-111148_Coronalert](https://user-images.githubusercontent.com/25742907/94987853-9ab21880-0569-11eb-9376-16b94e929852.jpg)
![Screenshot_20201003-111137_Coronalert](https://user-images.githubusercontent.com/25742907/94987854-9be34580-0569-11eb-99e2-51dcb6d33d82.jpg)

**Comment by IvoMerchiers** [comment]
Had the same issue on two devices:
A one plus 6 running android 10. The issue got resolved after switching to 4g instead of wifi.
A samsung galaxy s10e running android. Switching to 4g didn't help.

**Comment by ir-fuel** [comment]
The problem has been resolved in the mean time. Thanks for reporting!
