### ISSUE TITLE
Constant error 39508

### ISSUE THREAD

**Issue by swertz** [covid-be-app/cwa-app-android#93]
I keep getting messages saying "Un problème est survenu", with error code 39508, when updating my risk status.

The message redirects to the FAQ but I see no mention of this issue there.

Exposure logging seems to work fine.

Android version: 8.1.0 (any other infos needed?)

**Comment by leroynicolasalexi** [comment]
This error message still refers to the german FAQ.

Here is the revelant info:
https://www.coronawarn.app/en/faq/#API39508

**Comment by swertz** [comment]
Thanks for the clarification!

I've waited 24h before restarting the app and didn't get the message this time.
